# Generated by Django 4.2.6 on 2024-04-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loginapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
