# Generated by Django 4.2.6 on 2024-04-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieListapp', '0006_alter_movie_trailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(max_length=360),
        ),
    ]
