# Generated by Django 4.2.6 on 2024-05-02 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MovieListapp', '0008_remove_rating_rating_remove_review_text_rating_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
